version: '3'
services:
  streamlit:
    build: ./streamlit
    ports:
      - 8501:8501
    depends_on:
      - backend
    restart: always
    networks:
      - app
    container_name: streamlit

  backend:
    build: ./backend
    ports: 
      - 8000:8000
    restart: always
    networks:
      - app
    container_name: backend

networks:
  app:
    driver: bridge
