services:
  - type: web
    name: streamlit
    env: docker
    plan: free
    dockerfilePath: ./streamlit/Dockerfile
    autoDeploy: true

  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
