services:
  - type: web
    name: streamlit
    env: docker
    plan: free
    dockerfilePath: ./streamlit/Dockerfile
    buildCommand: ""
    startCommand: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
    autoDeploy: true

  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
